symbol1 = ['GOED', 'ZIVO', 'TYHT', 'PRVB', 'IMVT', 'TIRX', 'ETON', 'DAWN']
symbol2 = ['WPG', 'VTNR', 'LEDS', 'GTT', 'MOSY', 'AMC', 'CNST', 'UONE']
symbol3 = ['TGT', 'LOW', 'HD', 'NKE', 'TSLA', 'AAPL','NIO', 'Z', 'MSFT', 'WPG', 'VTNR', 'LEDS', 'GTT', 'MOSY', 'AMC', 'CNST', 'UONE']
symbol4 = ['EXFO', 'KBSF', 'LEDS', 'NEXT', 'LMNL']
symbol5 = ['AAPL','AMC','XP']
symbol6 = ['PFMT','LODE','CPSH','SCKT','PRT','CTHR','EMKR','CHCI','EGY','BW',
          'EXK','USDP','HBIO','III','PMBC','MHLD','OVID','AETUF','HL','KDOZF','CLNY',
          'ICL','SOL','WIT','EVC','SCGLY','PNNT','NL','ASX','WRTBY','BGCP','OXBR','MMMB']
symbol7 = ['PFMT','LODE','CPSH','SCKT','PRT']
symbol8 = ['CLOV','IHT','NEXT','AEHL']
symbol9 = ['ATOS','MCF','RMED','HOOK','ACRS']
symbol10 = ['LOTZ','EVK','ASTS']
symbol11 = ['F','TGT','AAPL','T','MSFT','IBM','IRM','AMC']
symbol12 = ['JZXN','AAPL','RIDE']
symbol13 = ['TGT']
symbol14 = ['AAPL','TGT','CLOV','TSLA','MSFT','WPG']
symbol15 = ['EURUSD=X']
symbol16 = ['TSLA','FCX','NUE','EXPD','AMAT']
symbol17 = ['AMC','CLOV','ALF','CLSD','TRCH','OBLN','CLSD']